# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d077eb9507c59b4fbeb53103efd6a579"
name = "ViewList"
handle = "customers-data"
application_url = "https://hardware-idaho-master-persian.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-c89f3673.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_orders,read_products,write_customers,write_draft_orders,write_orders,write_products"

[auth]
redirect_urls = [
  "https://hardware-idaho-master-persian.trycloudflare.com/auth/callback",
  "https://hardware-idaho-master-persian.trycloudflare.com/auth/shopify/callback",
  "https://hardware-idaho-master-persian.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
